; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html



[env:proton]
platform = https://github.com/norandomtechie/platform-raspberrypi.git#feature/proton-picosdk-support
board = proton
framework = picosdk
debug_tool = picoprobe
build_src_flags = -O0
upload_protocol = picoprobe
monitor_speed = 115200
build_flags = 
	-Iinclude/
    -std=c++17